CFLAGS = -lm

all:	2-to-n binary-search fac-time insert-sort merge-sort seq-search triple

2-to-n:	2-to-n.c
	gcc 2-to-n.c -o 2-to-n $(CFLAGS) 

binary-search:	binary-search.c
	gcc binary-search.c -o binary-search

fac-time:	fac-time.c
	gcc fac-time.c -o fac-time

insert-sort:	insert-sort.c
	gcc insert-sort.c -o insert-sort

merge-sort:	merge-sort.c
	gcc merge-sort.c -o merge-sort

seq-search:	seq-search.c
	gcc seq-search.c -o seq-search

triple:	triple.c
	gcc triple.c -o triple

clean:
	rm 2-to-n binary-search fac-time insert-sort merge-sort seq-search triple

